import { useEffect, useState } from "react";
import { Music } from "./types";
import { Player } from "./Player";

export function PlayList() {
  const [selectedMusic, setSelectedMusic] = useState<null | Music>(null);

  useEffect(() => {
    function parseCurrentPath() {
      const path = window.location.pathname;
      let match = path.match(/^\/music\/([^\/]+)\/?$/);
      if (match) {
        const matchedMusicName = decodeURI(match[1]);
        for (const music of musicList) {
          if (music.name === matchedMusicName) {
            setSelectedMusic(music);
          }
        }
      } else {
        setSelectedMusic(null);
        document.title = "music";
        window.history.pushState({}, "", `/music/`);
      }
    }
    parseCurrentPath();
    window.addEventListener("popstate", parseCurrentPath);
    return () => {
      window.removeEventListener("popstate", parseCurrentPath);
    };
  }, []);

  useEffect(() => {
    if (selectedMusic === null) {
      return;
    }
    if (!decodeURI(window.location.pathname).endsWith(selectedMusic.name)) {
      document.title = selectedMusic.name;
      window.history.pushState({}, "", `/music/${selectedMusic.name}`);
    }
  }, [selectedMusic]);

  if (selectedMusic === null) {
    return (
      <div className="play-list">
        {musicList.map((music, index) => (
          <div
            key={music.name}
            className="item"
            onClick={() => {
              setSelectedMusic(music);
            }}
          >
            {music.name}
          </div>
        ))}
      </div>
    );
  } else {
    return <Player music={selectedMusic} key={selectedMusic.name} />;
  }
}

const musicList: Music[] = [
  {
    name: "カタオモイ",
    url: "res-1/kataomoi.mp3",
    lyrics: [
      "00:01.00 <ruby>例<rt>たとえ</rt></ruby>ば<ruby>君<rt>きみ</rt></ruby>の<ruby>颜<rt>かお</rt></ruby>に<ruby>昔<rt>むかし</rt></ruby>より",
      "00:05.67 シワが<ruby>増<rt>ふ</rt></ruby>えても",
      "00:08.43 それでもいいんだ",
      "00:10.57 <ruby>僕<rt>ぼく</rt></ruby>がギターを",
      "00:12.70 <ruby>思<rt>おも</rt></ruby>うように<ruby>弾<rt>ひ</rt></ruby>けなくなっても",
      "00:15.70 <ruby>心<rt>こころ</rt></ruby>の<ruby>歌<rt>うた</rt></ruby>は<ruby>君<rt>きみ</rt></ruby>で<ruby>溢<rt>あふ</rt></ruby>れているよ",
      "00:20.10 <ruby>高<rt>たか</rt></ruby>い<ruby>声<rt>こえ</rt></ruby>も<ruby>出<rt>だ</rt></ruby>せずに<ruby>思<rt>おも</rt></ruby>い<ruby>通<rt>どお</rt></ruby>り<ruby>歌<rt>うた</rt></ruby>えない",
      "00:25.25 それでもうなずきながら<ruby>一绪<rt>いっしょ</rt></ruby>に<ruby>歌<rt>うた</rt></ruby>ってくれるかな",
      "00:30.25 <ruby>割<rt>わ</rt></ruby>れんばかりの<ruby>拍手<rt>はくしゅ</rt></ruby>も <ruby>响<rt>ひび</rt></ruby>き<ruby>渡<rt>わた</rt></ruby>る<ruby>歓声<rt>かんせい</rt></ruby>もいらない",
      "00:35.25 <ruby>君<rt>きみ</rt></ruby>だけ <ruby>分<rt>わ</rt></ruby>かってよ <ruby>分<rt>わ</rt></ruby>かってよ",
      "00:40.25 Darlin' <ruby>梦<rt>ゆめ</rt></ruby>が<ruby>叶<rt>かな</rt></ruby>ったの",
      "00:45.25 お<ruby>似合<rt>にあ</rt></ruby>いの<ruby>言叶<rt>ことば</rt></ruby>が<ruby>见<rt>み</rt></ruby>つからないよ",
      "00:50.36 Darlin' <ruby>梦<rt>ゆめ</rt></ruby>が<ruby>叶<rt>かな</rt></ruby>ったの",
      "00:54.70 「<ruby>爱<rt>あい</rt></ruby>してる」",
      "00:57.70 たった<ruby>一度<rt>いちど</rt></ruby>の たった<ruby>一人<rt>ひとり</rt></ruby>の",
      "01:02.25 <ruby>生<rt>う</rt></ruby>まれてきた<ruby>幸<rt>しあわ</rt></ruby>せ<ruby>味<rt>あじ</rt></ruby>わって るんだよ",
      "01:07.70 <ruby>今日<rt>きょう</rt></ruby>がメインディッシュで",
      "01:09.70 <ruby>终<rt>お</rt></ruby>わりの<ruby>日<rt>ひ</rt></ruby>には<ruby>甘酸<rt>あまず</rt></ruby>っぱいデザートを<ruby>食<rt>た</rt></ruby>べるの",
      "01:13.70 <ruby>山<rt>やま</rt></ruby>も<ruby>谷<rt>たに</rt></ruby>も<ruby>全部<rt>ぜんぶ</rt></ruby>フルコースで",
      "01:17.25 <ruby>気<rt>き</rt></ruby>が<ruby>利<rt>き</rt></ruby>くような<ruby>言叶<rt>ことば</rt></ruby>はいらない",
      "01:20.25 <ruby>素晴<rt>すば</rt></ruby>らしい<ruby>特别<rt>とくべつ</rt></ruby>もいらない",
      "01:22.70 ただずっとずっと<ruby>侧<rt>そば</rt></ruby>に<ruby>置<rt>お</rt></ruby>いていてよ",
      "01:27.56 <ruby>僕<rt>ぼく</rt></ruby>の<ruby>想<rt>おも</rt></ruby>いは<ruby>歳<rt>とし</rt></ruby>をとると<ruby>増<rt>ふ</rt></ruby>えてくばっかだ <ruby>好<rt>す</rt></ruby>きだよ",
      "01:33.25 <ruby>分<rt>わ</rt></ruby>かってよ <ruby>分<rt>わ</rt></ruby>かってよ",
      "01:36.70 ねえ darlin' <ruby>梦<rt>ゆめ</rt></ruby>が<ruby>叶<rt>かな</rt></ruby>ったの",
      "01:41.70 お<ruby>似合<rt>にあ</rt></ruby>いの<ruby>言叶<rt>ことば</rt></ruby>が<ruby>见<rt>み</rt></ruby>つからないよ",
      "01:47.25 Darlin' <ruby>梦<rt>ゆめ</rt></ruby>が<ruby>叶<rt>かな</rt></ruby>ったの",
      "01:51.70 <ruby>爱<rt>あい</rt></ruby>が<ruby>溢<rt>あふ</rt></ruby>れていく",
      "01:57.09 ...",
      "02:19.25 <ruby>君<rt>きみ</rt></ruby>が<ruby>僕<rt>ぼく</rt></ruby>を<ruby>忘<rt>わす</rt></ruby>れてしまっても ちょっと<ruby>辛<rt>つら</rt></ruby>いけど",
      "02:26.69 それでもいいから",
      "02:29.25 <ruby>僕<rt>ぼく</rt></ruby>より<ruby>先<rt>さき</rt></ruby>にどこか<ruby>远<rt>とお</rt></ruby>くに",
      "02:34.03 <ruby>旅立<rt>たびだ</rt></ruby>つことは <ruby>绝対<rt>ぜったい</rt></ruby><ruby> 许<rt>ゆる</rt></ruby>さないから",
      "02:38.69 <ruby>生<rt>う</rt></ruby>まれ<ruby>変<rt>か</rt></ruby>わったとしても <ruby>出会<rt>であ</rt></ruby>い方が<ruby>最悪<rt>さいあく</rt></ruby>でも",
      "02:44.25 また<ruby>僕<rt>ぼく</rt></ruby>は<ruby>君<rt>きみ</rt></ruby>に <ruby>恋<rt>こい</rt></ruby>するんだよ",
      "02:49.25 <ruby>僕<rt>ぼく</rt></ruby>の<ruby>心<rt>こころ</rt></ruby>は<ruby>君<rt>きみ</rt></ruby>にいつも<ruby>片想<rt>かたおも</rt></ruby>い <ruby>好<rt>す</rt></ruby>きだよ",
      "02:54.69 <ruby>分<rt>わ</rt></ruby>かってよ <ruby>分<rt>わ</rt></ruby>かってよ <ruby>分<rt>わ</rt></ruby>かってよ",
      "03:01.25 Darlin' <ruby>梦<rt>ゆめ</rt></ruby>が<ruby>叶<rt>かな</rt></ruby>ったの",
      "03:06.25 お<ruby>似合<rt>にあ</rt></ruby>いの<ruby>言叶<rt>ことば</rt></ruby>が<ruby>见<rt>み</rt></ruby>つからないよ",
      "03:11.25 Darlin' <ruby>梦<rt>ゆめ</rt></ruby>が<ruby>叶<rt>かな</rt></ruby>ったの",
      "03:16.25 ねえ darlin' 「<ruby>爱<rt>あい</rt></ruby>してる」",
      "03:24.06 ...",
    ],
  },
  {
    name: "アイドル",
    url: "res-1/idol.mp3",
    lyrics: [
      "00:00.27 <ruby>無敵<rt>むてき</rt></ruby>の<ruby>笑顔<rt>えがお</rt></ruby>で<ruby>荒<rt>あ</rt></ruby>らすメディア",
      "00:03.28 <ruby>知<rt>し</rt></ruby>りたいその<ruby>秘密<rt>ひみつ</rt></ruby>ミステリアス",
      "00:05.92 <ruby>抜<rt>ぬ</rt></ruby>けてるとこさえ<ruby>彼女<rt>かのじょ</rt></ruby>のエリア",
      "00:08.98 <ruby>完璧<rt>かんぺき</rt></ruby>で<ruby>嘘<rt>うそ</rt></ruby>つきな<ruby>君<rt>きみ</rt></ruby>は",
      "00:11.67 <ruby>天才的<rt>てんさいてき</rt></ruby>なアイドル<ruby>様<rt>さま</rt></ruby>",
      "00:14.37 ...",
      "00:17.21 <ruby>今日<rt>きょう</rt></ruby><ruby>何<rt>なに</rt></ruby><ruby>食<rt>た</rt></ruby>べた?",
      "00:18.65 <ruby>好<rt>す</rt></ruby>きな<ruby>本<rt>ほん</rt></ruby>は?",
      "00:20.08 <ruby>遊<rt>あそ</rt></ruby>びに<ruby>行<rt>い</rt></ruby>くならどこに<ruby>行<rt>い</rt></ruby>くの?",
      "00:23.12 <ruby>何<rt>なに</rt></ruby>も<ruby>食<rt>た</rt></ruby>べてない",
      "00:24.49 それは<ruby>内緒<rt>ないしょ</rt></ruby>",
      "00:25.95 <ruby>何<rt>なに</rt></ruby>を<ruby>聞<rt>き</rt></ruby>かれてものらりくらり",
      "00:28.49 -",
      "00:28.53 そう<ruby>淡々<rt>たんたん</rt></ruby>と",
      "00:29.83 だけど<ruby>燦々<rt>さんさん</rt></ruby>と",
      "00:31.30 <ruby>見<rt>み</rt></ruby>えそうで<ruby>見<rt>み</rt></ruby>えない<ruby>秘密<rt>ひみつ</rt></ruby>は<ruby>蜜<rt>みつ</rt></ruby>の<ruby>味<rt>あじ</rt></ruby>",
      "00:34.33 あれもないないない",
      "00:35.64 これもないないない",
      "00:37.02 <ruby>好<rt>す</rt></ruby>きなタイプは?",
      "00:38.22 <ruby>相手<rt>あいて</rt></ruby>は?",
      "00:38.97 さあ<ruby>答<rt>こた</rt></ruby>えて",
      "00:40.10 -",
      "00:40.20 「<ruby>誰<rt>だれ</rt></ruby>かを<ruby>好<rt>す</rt></ruby>きになること なんて<ruby>私<rt>わたし</rt></ruby><ruby>分<rt>わ</rt></ruby>からなくてさ」",
      "00:46.00 <ruby>嘘<rt>うそ</rt></ruby>か<ruby>本当<rt>ほんとう</rt></ruby>か<ruby>知<rt>し</rt></ruby>り<ruby>得<rt>え</rt></ruby>ない",
      "00:48.89 そんな<ruby>言葉<rt>ことば</rt></ruby>にまた<ruby>一人<rt>ひとり</rt></ruby><ruby>堕<rt>お</rt></ruby>ちる",
      "00:52.59 また<ruby>好<rt>す</rt></ruby>きにさせる",
      "00:54.65 -",
      "00:54.69 <ruby>誰<rt>だれ</rt></ruby>もが<ruby>目<rt>め</rt></ruby>を<ruby>奪<rt>うば</rt></ruby>われていく",
      "00:57.49 <ruby>君<rt>きみ</rt></ruby>は<ruby>完璧<rt>かんぺき</rt></ruby>で<ruby>究極<rt>きゅうきょく</rt></ruby>のアイドル",
      "01:00.78 <ruby>金輪際<rt>こんりんざい</rt></ruby><ruby>現<rt>あらわ</rt></ruby>れない",
      "01:03.36 <ruby>一番星<rt>いちばんぼし</rt></ruby>の<ruby>生<rt>う</rt></ruby>まれ<ruby>変<rt>か</rt></ruby>わり",
      "01:07.12 その<ruby>笑顔<rt>えがお</rt></ruby>で<ruby>愛<rt>あい</rt></ruby>してるで",
      "01:09.84 <ruby>誰<rt>だれ</rt></ruby>も<ruby>彼<rt>かれ</rt></ruby>も<ruby>虜<rt>とりこ</rt></ruby>にしていく",
      "01:12.95 その<ruby>瞳<rt>ひとみ</rt></ruby>がその<ruby>言葉<rt>ことば</rt></ruby>が",
      "01:15.26 <ruby>嘘<rt>うそ</rt></ruby>でもそれは<ruby>完全<rt>かんぜん</rt></ruby>なアイ",
      "01:18.11 -",
      "01:18.41 はいはいあの<ruby>子<rt>こ</rt></ruby>は<ruby>特別<rt>とくべつ</rt></ruby>です",
      "01:21.33 <ruby>我々<rt>われわれ</rt></ruby>はハナからおまけです",
      "01:24.02 お<ruby>星様<rt>ほしさま</rt></ruby>の<ruby>引<rt>ひ</rt></ruby>き<ruby>立<rt>た</rt></ruby>て<ruby>役<rt>やく</rt></ruby>B です",
      "01:27.04 <ruby>全<rt>すべ</rt></ruby>てがあの<ruby>子<rt>こ</rt></ruby>のお<ruby>陰<rt>かげ</rt></ruby>なわけない",
      "01:30.13 <ruby>洒落臭<rt>しゃらくさ</rt></ruby>い",
      "01:30.79 <ruby>妬<rt>ねた</rt></ruby>み<ruby>嫉妬<rt>しっと</rt></ruby>なんてないわけがない",
      "01:33.02 これはネタじゃない",
      "01:34.00 からこそ<ruby>許<rt>ゆる</rt></ruby>せない",
      "01:35.14 <ruby>完璧<rt>かんぺき</rt></ruby>じゃない<ruby>君<rt>きみ</rt></ruby>じゃ<ruby>許<rt>ゆる</rt></ruby>せない",
      "01:37.24 <ruby>自分<rt>じぶん</rt></ruby>を<ruby>許<rt>ゆる</rt></ruby>せない",
      "01:38.36 <ruby>誰<rt>だれ</rt></ruby>よりも<ruby>強<rt>つよ</rt></ruby>い<ruby>君<rt>きみ</rt></ruby><ruby>以外<rt>いがい</rt></ruby>は<ruby>認<rt>みと</rt></ruby>めない",
      "01:40.94 -",
      "01:40.96 <ruby>誰<rt>だれ</rt></ruby>もが<ruby>信<rt>しん</rt></ruby>じ<ruby>崇<rt>あが</rt></ruby>めてる",
      "01:43.82 まさに<ruby>最強<rt>さいきょう</rt></ruby>で<ruby>無敵<rt>むてき</rt></ruby>のアイドル",
      "01:47.02 <ruby>弱点<rt>じゃくてん</rt></ruby>なんて<ruby>見当<rt>みあ</rt></ruby>たらない",
      "01:49.67 <ruby>一番星<rt>いちばんぼし</rt></ruby>を<ruby>宿<rt>やど</rt></ruby>している",
      "01:52.62 <ruby>弱<rt>よわ</rt></ruby>いとこなんて<ruby>見<rt>み</rt></ruby>せちゃダメダメ",
      "01:55.75 <ruby>知<rt>し</rt></ruby>りたくないとこは<ruby>見<rt>み</rt></ruby>せずに",
      "01:58.63 <ruby>唯一無二<rt>ゆいつむに</rt></ruby>じゃなくちゃイヤイヤ",
      "02:01.48 それこそ<ruby>本物<rt>ほんもの</rt></ruby>のアイ",
      "02:04.29 -",
      "02:04.74 <ruby>得意<rt>とくい</rt></ruby>の<ruby>笑顔<rt>えがお</rt></ruby>で<ruby>沸<rt>わ</rt></ruby>かすメディア",
      "02:08.05 <ruby>隠<rt>かく</rt></ruby>しきるこの<ruby>秘密<rt>ひみつ</rt></ruby>だけは",
      "02:10.88 <ruby>愛<rt>あい</rt></ruby>してるって<ruby>嘘<rt>うそ</rt></ruby>で<ruby>積<rt>つ</rt></ruby>むキャリア",
      "02:14.39 これこそ<ruby>私<rt>わたし</rt></ruby>なりの<ruby>愛<rt>あい</rt></ruby>だ",
      "02:17.68 <ruby>流<rt>なが</rt></ruby>れる<ruby>汗<rt>あせ</rt></ruby>も<ruby>綺麗<rt>きれい</rt></ruby>なアクア",
      "02:20.74 ルビーを<ruby>隠<rt>かく</rt></ruby>したこの<ruby>瞼<rt>まぶた</rt></ruby>",
      "02:23.65 <ruby>歌<rt>うた</rt></ruby>い<ruby>踊<rt>おど</rt></ruby>り<ruby>舞<rt>ま</rt></ruby>う<ruby>私<rt>わたし</rt></ruby>はマリア",
      "02:27.15 そう<ruby>嘘<rt>うそ</rt></ruby>はとびきりの<ruby>愛<rt>あい</rt></ruby>だ",
      "02:30.32 -",
      "02:31.20 <ruby>誰<rt>だれ</rt></ruby>かに<ruby>愛<rt>あい</rt></ruby>されたことも",
      "02:34.32 <ruby>誰<rt>だれ</rt></ruby>かのこと<ruby>愛<rt>あい</rt></ruby>したことも",
      "02:37.71 ない",
      "02:38.10 そんな<ruby>私<rt>わたし</rt></ruby>の<ruby>嘘<rt>うそ</rt></ruby>が いつか<ruby>本当<rt>ほんとう</rt></ruby>になること",
      "02:43.54 <ruby>信<rt>しん</rt></ruby>じてる",
      "02:44.71 -",
      "02:44.82 いつかきっと<ruby>全部<rt>ぜんぶ</rt></ruby><ruby>手<rt>て</rt></ruby>に<ruby>入<rt>い</rt></ruby>れる",
      "02:47.73 <ruby>私<rt>わたし</rt></ruby>はそう<ruby>欲張<rt>よくば</rt></ruby>りなアイドル",
      "02:51.07 <ruby>等身大<rt>とうしんだい</rt></ruby>でみんなのこと",
      "02:53.56 ちゃんと<ruby>愛<rt>あい</rt></ruby>したいから",
      "02:56.49 <ruby>今日<rt>きょう</rt></ruby>も<ruby>嘘<rt>うそ</rt></ruby>をつくの",
      "02:58.77 この<ruby>言葉<rt>ことば</rt></ruby>がいつか<ruby>本当<rt>ほんとう</rt></ruby>になる<ruby>日<rt>ひ</rt></ruby>を<ruby>願<rt>ねが</rt></ruby>って",
      "03:03.14 それでもまだ",
      "03:04.54 <ruby>君<rt>きみ</rt></ruby>と<ruby>君<rt>きみ</rt></ruby>にだけは<ruby>言<rt>い</rt></ruby>えずにいたけど",
      "03:08.93 やっと<ruby>言<rt>い</rt></ruby>えた",
      "03:10.38 これは<ruby>絶対<rt>ぜったい</rt></ruby><ruby>嘘<rt>うそ</rt></ruby>じゃない",
      "03:12.52 <ruby>愛<rt>あい</rt></ruby>してる",
      "03:14.51 ...",
    ],
  },
  {
    name: "群青",
    url: "res-1/gunjou.mp3",
    lyrics: [
      "00:00.97 <ruby>嗚呼<rt>ああ</rt></ruby>、いつもの<ruby>様<rt>よう</rt></ruby>に",
      "00:03.52 <ruby>過<rt>す</rt></ruby>ぎる<ruby>日々<rt>ひび</rt></ruby>に あくびが<ruby>出<rt>で</rt></ruby>る",
      "00:07.05 さんざめく<ruby>夜<rt>よる</rt></ruby>、<ruby>越<rt>こ</rt></ruby>え、<ruby>今日<rt>きょう</rt></ruby>も",
      "00:11.07 <ruby>渋谷<rt>しぶや</rt></ruby>の<ruby>街<rt>まち</rt></ruby>に<ruby>朝<rt>あさ</rt></ruby>が<ruby>降<rt>ふ</rt></ruby>る",
      "00:14.95 どこか<ruby>虚<rt>むな</rt></ruby>しいような",
      "00:17.75 そんな<ruby>気持<rt>きも</rt></ruby>ち",
      "00:19.63 つまらないな",
      "00:21.28 でもそれでいい",
      "00:23.07 そんなもんさ",
      "00:24.88 これでいい",
      "00:25.86 <ruby>知<rt>し</rt></ruby>らず<ruby>知<rt>し</rt></ruby>らず<ruby>隠<rt>かく</rt></ruby>してた",
      "00:28.60 <ruby>本当<rt>ほんとう</rt></ruby>の<ruby>声<rt>こえ</rt></ruby>を<ruby>響<rt>ひび</rt></ruby>かせてよ、ほら",
      "00:33.03 <ruby>見<rt>み</rt></ruby>ないフリしていても",
      "00:35.70 <ruby>確<rt>たし</rt></ruby>かにそこにある",
      "00:40.17 <ruby>感<rt>かん</rt></ruby>じたままに<ruby>描<rt>えが</rt></ruby>く",
      "00:43.02 <ruby>自分<rt>じぶん</rt></ruby>で<ruby>選<rt>えら</rt></ruby>んだその<ruby>色<rt>いろ</rt></ruby>で",
      "00:46.63 <ruby>眠<rt>ねむ</rt></ruby>い<ruby>空気纏<rt>くうきまと</rt></ruby>う<ruby>朝<rt>あさ</rt></ruby>に",
      "00:50.08 <ruby>訪<rt>おとず</rt></ruby>れた<ruby>青<rt>あお</rt></ruby>い<ruby>世界<rt>せかい</rt></ruby>",
      "00:53.75 <ruby>好<rt>す</rt></ruby>きなものを<ruby>好<rt>す</rt></ruby>きだと<ruby>言<rt>い</rt></ruby>う",
      "00:57.31 <ruby>怖<rt>こわ</rt></ruby>くて<ruby>仕方<rt>しかた</rt></ruby>ないけど",
      "01:00.45 <ruby>本当<rt>ほんとう</rt></ruby>の<ruby>自分<rt>じぶん</rt></ruby>",
      "01:02.61 <ruby>出会<rt>であ</rt></ruby>えた<ruby>気<rt>き</rt></ruby>がしたんだ",
      "01:05.54 ...",
      "01:15.68 <ruby>嗚呼<rt>ああ</rt></ruby>、<ruby>手<rt>て</rt></ruby>を<ruby>伸<rt>の</rt></ruby>ばせば<ruby>伸<rt>の</rt></ruby>ばすほどに",
      "01:19.91 <ruby>遠<rt>とお</rt></ruby>くへゆく",
      "01:21.86 <ruby>思<rt>おも</rt></ruby>うようにいかない、<ruby>今日<rt>きょう</rt></ruby>も",
      "01:25.73 また<ruby>慌<rt>あわ</rt></ruby>ただしくもがいてる",
      "01:29.44 <ruby>悔<rt>くや</rt></ruby>しい<ruby>気持<rt>きも</rt></ruby>ちも",
      "01:31.16 ただ<ruby>情<rt>なさ</rt></ruby>けなくて",
      "01:34.20 <ruby>涙<rt>なみだ</rt></ruby>が<ruby>出<rt>で</rt></ruby>る",
      "01:35.99 <ruby>踏<rt>ふ</rt></ruby>み<ruby>込<rt>こ</rt></ruby>むほど",
      "01:37.79 <ruby>苦<rt>くる</rt></ruby>しくなる",
      "01:39.50 <ruby>痛<rt>いた</rt></ruby>くもなる",
      "01:44.16 <ruby>感<rt>かん</rt></ruby>じたままに<ruby>進<rt>すす</rt></ruby>む",
      "01:47.01 <ruby>自分<rt>じぶん</rt></ruby>で<ruby>選<rt>えら</rt></ruby>んだこの<ruby>道<rt>みち</rt></ruby>を",
      "01:50.54 <ruby>重<rt>おも</rt></ruby>いまぶた<ruby>擦<rt>こす</rt></ruby>る<ruby>夜<rt>よる</rt></ruby>に",
      "01:54.16 しがみついた<ruby>青<rt>あお</rt></ruby>い<ruby>誓<rt>ちか</rt></ruby>い",
      "01:57.77 <ruby>好<rt>す</rt></ruby>きなことを<ruby>続<rt>つづ</rt></ruby>けること",
      "02:01.11 それは「<ruby>楽<rt>たの</rt></ruby>しい」だけじゃない",
      "02:04.38 <ruby>本当<rt>ほんとう</rt></ruby>にできる？",
      "02:06.60 <ruby>不安<rt>ふあん</rt></ruby>になるけど",
      "02:08.98 <ruby>何枚<rt>なんまい</rt></ruby>でも",
      "02:10.38 ほら<ruby>何枚<rt>なんまい</rt></ruby>でも",
      "02:12.08 <ruby>自信<rt>じしん</rt></ruby>がないから<ruby>描<rt>えが</rt></ruby>いてきたんだよ",
      "02:15.65 <ruby>何回<rt>なんかい</rt></ruby>でも",
      "02:17.40 ほら<ruby>何回<rt>なんかい</rt></ruby>でも",
      "02:19.20 <ruby>積<rt>つ</rt></ruby>み<ruby>上<rt>あ</rt></ruby>げてきたことが<ruby>武器<rt>ぶき</rt></ruby>になる",
      "02:22.76 <ruby>周<rt>まわ</rt></ruby>りを<ruby>見<rt>み</rt></ruby>たって",
      "02:24.44 <ruby>誰<rt>だれ</rt></ruby>と<ruby>比<rt>くら</rt></ruby>べたって",
      "02:26.18 <ruby>僕<rt>ぼく</rt></ruby>にしかできないことはなんだ",
      "02:29.85 <ruby>今<rt>いま</rt></ruby>でも<ruby>自信<rt>じしん</rt></ruby>なんかない",
      "02:33.35 それでも",
      "02:35.78 <ruby>感<rt>かん</rt></ruby>じたことない<ruby>気持<rt>きも</rt></ruby>ち",
      "02:38.56 <ruby>知<rt>し</rt></ruby>らずにいた<ruby>想<rt>おも</rt></ruby>い",
      "02:41.80 あの<ruby>日踏<rt>ひふ</rt></ruby>み<ruby>出<rt>だ</rt></ruby>して",
      "02:43.96 <ruby>初<rt>はじ</rt></ruby>めて<ruby>感<rt>かん</rt></ruby>じたこの<ruby>痛<rt>いた</rt></ruby>みも<ruby>全部<rt>ぜんぶ</rt></ruby>",
      "02:49.18 <ruby>好<rt>す</rt></ruby>きなものと<ruby>向<rt>む</rt></ruby>き<ruby>合<rt>あ</rt></ruby>うことで",
      "02:52.73 <ruby>触<rt>ふ</rt></ruby>れたまだ<ruby>小<rt>ちい</rt></ruby>さな<ruby>光<rt>ひかり</rt></ruby>",
      "02:55.97 <ruby>大丈夫<rt>だいじょうぶ</rt></ruby>、<ruby>行<rt>い</rt></ruby>こう、あとは<ruby>楽<rt>たの</rt></ruby>しむだけだ",
      "03:04.19 <ruby>全<rt>すべ</rt></ruby>てを<ruby>賭<rt>か</rt></ruby>けて<ruby>描<rt>えが</rt></ruby>く",
      "03:06.91 <ruby>自分<rt>じぶん</rt></ruby>にしか<ruby>出<rt>だ</rt></ruby>せない<ruby>色<rt>いろ</rt></ruby>で",
      "03:10.48 <ruby>朝<rt>あさ</rt></ruby>も<ruby>夜<rt>よる</rt></ruby>も<ruby>走<rt>はし</rt></ruby>り<ruby>続<rt>つづ</rt></ruby>け",
      "03:13.30 <ruby>見<rt>み</rt></ruby>つけ<ruby>出<rt>だ</rt></ruby>した<ruby>青<rt>あお</rt></ruby>い<ruby>光<rt>ひかり</rt></ruby>",
      "03:17.68 <ruby>好<rt>す</rt></ruby>きなものと<ruby>向<rt>む</rt></ruby>き<ruby>合<rt>あ</rt></ruby>うこと",
      "03:21.15 <ruby>今<rt>いま</rt></ruby>だって<ruby>怖<rt>こわ</rt></ruby>いことだけど",
      "03:24.50 もう<ruby>今<rt>いま</rt></ruby>はあの<ruby>日<rt>ひ</rt></ruby>の<ruby>透明<rt>とうめい</rt></ruby>な<ruby>僕<rt>ぼく</rt></ruby>じゃない",
      "03:32.07 ありのままの",
      "03:33.69 かけがえの<ruby>無<rt>な</rt></ruby>い<ruby>僕<rt>ぼく</rt></ruby>だ",
      "03:36.13 <ruby>知<rt>し</rt></ruby>らず<ruby>知<rt>し</rt></ruby>らず<ruby>隠<rt>かく</rt></ruby>してた",
      "03:38.78 <ruby>本当<rt>ほんとう</rt></ruby>の<ruby>声<rt>こえ</rt></ruby>を<ruby>響<rt>ひび</rt></ruby>かせてよ、ほら",
      "03:43.15 <ruby>見<rt>み</rt></ruby>ないフリしていても",
      "03:45.92 <ruby>確<rt>たし</rt></ruby>かにそこに<ruby>今<rt>いま</rt></ruby>もそこにあるよ",
      "03:50.47 <ruby>知<rt>し</rt></ruby>らず<ruby>知<rt>し</rt></ruby>らず<ruby>隠<rt>かく</rt></ruby>してた",
      "03:53.18 <ruby>本当<rt>ほんとう</rt></ruby>の<ruby>声<rt>こえ</rt></ruby>を<ruby>響<rt>ひび</rt></ruby>かせてよ、さあ",
      "03:57.43 <ruby>見<rt>み</rt></ruby>ないフリしていても",
      "04:00.10 <ruby>確<rt>たし</rt></ruby>かにそこに<ruby>君<rt>きみ</rt></ruby>の<ruby>中<rt>なか</rt></ruby>に",
      "04:07.39 ...",
    ],
  },
  {
    name: "夜に駆ける",
    url: "res-1/yoru-ni-kakeru.mp3",
    lyrics: [
      "00:01.43 <ruby>沈<rt>しず</rt></ruby>むように<ruby>溶<rt>と</rt></ruby>けてゆくように",
      "00:08.83 <ruby>二人<rt>ふたり</rt></ruby>だけの<ruby>空<rt>そら</rt></ruby>が<ruby>広<rt>ひろ</rt></ruby>がる<ruby>夜<rt>よる</rt></ruby>に",
      "00:15.00 -",
      "00:31.48 「さよなら」だけだった",
      "00:34.05 その<ruby>一言<rt>ひとこと</rt></ruby>で<ruby>全<rt>すべ</rt></ruby>てが<ruby>分<rt>わ</rt></ruby>かった",
      "00:37.76 <ruby>日<rt>ひ</rt></ruby>が<ruby>沈<rt>しず</rt></ruby>み<ruby>出<rt>だ</rt></ruby>した<ruby>空<rt>そら</rt></ruby>と<ruby>君<rt>きみ</rt></ruby>の<ruby>姿<rt>すがた</rt></ruby>",
      "00:42.12 フェンス<ruby>越<rt>ご</rt></ruby>しに<ruby>重<rt>かさ</rt></ruby>なっていた",
      "00:46.12 <ruby>初<rt>はじ</rt></ruby>めて<ruby>会<rt>あ</rt></ruby>った<ruby>日<rt>ひ</rt></ruby>から",
      "00:48.80 <ruby>僕<rt>ぼく</rt></ruby>の<ruby>心<rt>こころ</rt></ruby>の<ruby>全<rt>すべ</rt></ruby>てを<ruby>奪<rt>うば</rt></ruby>った",
      "00:52.41 どこか<ruby>儚<rt>はかな</rt></ruby>い<ruby>空気<rt>くうき</rt></ruby>を<ruby>纏<rt>まと</rt></ruby>う<ruby>君<rt>きみ</rt></ruby>は",
      "00:56.85 <ruby>寂<rt>さび</rt></ruby>しい<ruby>目<rt>め</rt></ruby>をしてたんだ",
      "01:00.08 いつだってチックタックと",
      "01:02.11 <ruby>鳴<rt>な</rt></ruby>る<ruby>世界<rt>せかい</rt></ruby>で<ruby>何度<rt>なんど</rt></ruby>だってさ",
      "01:03.95 <ruby>触<rt>ふ</rt></ruby>れる<ruby>心無<rt>こころな</rt></ruby>い<ruby>言葉<rt>ことば</rt></ruby>うるさい<ruby>声<rt>こえ</rt></ruby>に",
      "01:05.91 <ruby>涙<rt>なみだ</rt></ruby>が<ruby>零<rt>おぼ</rt></ruby>れそうでも",
      "01:08.58 ありきたりな<ruby>喜<rt>よろこ</rt></ruby>びきっと<ruby>二人<rt>ふたり</rt></ruby>なら<ruby>見<rt>み</rt></ruby>つけられる",
      "01:14.94 <ruby>騒<rt>さわ</rt></ruby>がしい<ruby>日々<rt>ひび</rt></ruby>に<ruby>笑<rt>わら</rt></ruby>えない<ruby>君<rt>きみ</rt></ruby>に",
      "01:18.96 <ruby>思<rt>おも</rt></ruby>い<ruby>付<rt>つ</rt></ruby>く<ruby>限<rt>かぎ</rt></ruby>り<ruby>眩<rt>まぶ</rt></ruby>しい<ruby>明日<rt>あす</rt></ruby>を",
      "01:22.65 <ruby>明<rt>あ</rt></ruby>けない<ruby>夜<rt>よる</rt></ruby>に<ruby>落<rt>お</rt></ruby>ちてゆく<ruby>前<rt>まえ</rt></ruby>に",
      "01:26.35 <ruby>僕<rt>ぼく</rt></ruby>の<ruby>手<rt>て</rt></ruby>を<ruby>掴<rt>つか</rt></ruby>んでほら",
      "01:29.24 <ruby>忘<rt>わす</rt></ruby>れてしまいたくて<ruby>閉<rt>と</rt></ruby>じ<ruby>込<rt>こ</rt></ruby>めた<ruby>日々<rt>ひび</rt></ruby>も",
      "01:33.78 <ruby>抱<rt>だ</rt></ruby>きしめた<ruby>温<rt>ぬく</rt></ruby>もりで<ruby>溶<rt>と</rt></ruby>かすから",
      "01:37.49 <ruby>怖<rt>こわ</rt></ruby>くないよいつか<ruby>日<rt>ひ</rt></ruby>が<ruby>昇<rt>のぼ</rt></ruby>るまで",
      "01:41.77 <ruby>二人<rt>ふたり</rt></ruby>でいよう",
      "01:46.95 -",
      "01:58.30 <ruby>君<rt>きみ</rt></ruby>にしか<ruby>見<rt>み</rt></ruby>えない",
      "02:00.76 <ruby>何<rt>なに</rt></ruby>かを<ruby>見<rt>み</rt></ruby>つめる<ruby>君<rt>きみ</rt></ruby>が<ruby>嫌<rt>きら</rt></ruby>いだ",
      "02:04.51 <ruby>見惚<rt>みと</rt></ruby>れているかのような<ruby>恋<rt>こい</rt></ruby>するような",
      "02:08.83 そんな<ruby>顔<rt>かお</rt></ruby>が<ruby>嫌<rt>きら</rt></ruby>いだ",
      "02:12.58 <ruby>信<rt>しん</rt></ruby>じていたいけど<ruby>信<rt>しん</rt></ruby>じれないこと",
      "02:14.37 そんなのどうしたってきっと",
      "02:16.05 これからだっていくつもあってそのたんび<ruby>怒<rt>おこ</rt></ruby>って<ruby>泣<rt>な</rt></ruby>いていくの",
      "02:19.80 それでもきっといつかはきっと<ruby>僕<rt>ぼく</rt></ruby>らはきっと",
      "02:22.67 <ruby>分<rt>わ</rt></ruby>かり<ruby>合<rt>あ</rt></ruby>えるさ<ruby>信<rt>しん</rt></ruby>じてるよ",
      "02:28.78 -",
      "02:40.67 もう<ruby>嫌<rt>いや</rt></ruby>だって<ruby>疲<rt>つか</rt></ruby>れたんだって",
      "02:43.05 がむしゃらに<ruby>差<rt>さ</rt></ruby>し<ruby>伸<rt>の</rt></ruby>べた<ruby>僕<rt>ぼく</rt></ruby>の<ruby>手<rt>て</rt></ruby>を<ruby>振<rt>ふ</rt></ruby>り<ruby>払<rt>はら</rt></ruby>う<ruby>君<rt>きみ</rt></ruby>",
      "02:48.10 もう<ruby>嫌<rt>いや</rt></ruby>だって<ruby>疲<rt>つか</rt></ruby>れたよなんて",
      "02:50.42 <ruby>本当<rt>ほんとう</rt></ruby>は<ruby>僕<rt>ぼく</rt></ruby>も<ruby>言<rt>い</rt></ruby>いたいんだ",
      "02:54.72 ほらまたチックタックと",
      "02:56.50 <ruby>鳴<rt>な</rt></ruby>る<ruby>世界<rt>せかい</rt></ruby>で<ruby>何度<rt>なんど</rt></ruby>だってさ",
      "02:58.28 <ruby>君<rt>きみ</rt></ruby>の<ruby>為<rt>ため</rt></ruby>に<ruby>用意<rt>ようい</rt></ruby>した<ruby>言葉<rt>ことば</rt></ruby>どれも<ruby>届<rt>とど</rt></ruby>かない",
      "03:01.57 「<ruby>終<rt>お</rt></ruby>わりにしたい」だなんてさ",
      "03:03.90 <ruby>釣<rt>つ</rt></ruby>られて<ruby>言葉<rt>ことば</rt></ruby>にした<ruby>時<rt>とき</rt></ruby>",
      "03:05.91 <ruby>君<rt>きみ</rt></ruby>は<ruby>初<rt>はじ</rt></ruby>めて<ruby>笑<rt>わら</rt></ruby>った",
      "03:11.46 <ruby>騒<rt>さわ</rt></ruby>がしい<ruby>日々<rt>ひび</rt></ruby>に<ruby>笑<rt>わら</rt></ruby>えなくなっていた",
      "03:15.36 <ruby>僕<rt>ぼく</rt></ruby>の<ruby>目<rt>め</rt></ruby>に<ruby>映<rt>うつ</rt></ruby>る<ruby>君<rt>きみ</rt></ruby>は<ruby>綺麗<rt>きれい</rt></ruby>だ",
      "03:19.08 <ruby>明<rt>あ</rt></ruby>けない<ruby>夜<rt>よる</rt></ruby>に<ruby>溢<rt>こぼ</rt></ruby>れた<ruby>涙<rt>なみだ</rt></ruby>も",
      "03:22.77 <ruby>君<rt>きみ</rt></ruby>の<ruby>笑顔<rt>えいがお</rt></ruby>に<ruby>溶<rt>と</rt></ruby>けていく",
      "03:27.91 <ruby>変<rt>か</rt></ruby>わらない<ruby>日々<rt>ひび</rt></ruby>に<ruby>泣<rt>な</rt></ruby>いていた<ruby>僕<rt>ぼく</rt></ruby>を",
      "03:31.93 <ruby>君<rt>きみ</rt></ruby>は<ruby>優<rt>やさ</rt></ruby>しく<ruby>終<rt>お</rt></ruby>わりへと<ruby>誘<rt>さそ</rt></ruby>う",
      "03:35.69 <ruby>沈<rt>しず</rt></ruby>むように<ruby>溶<rt>と</rt></ruby>けてゆくように",
      "03:39.35 <ruby>染<rt>し</rt></ruby>み<ruby>付<rt>つ</rt></ruby>いた<ruby>霧<rt>きり</rt></ruby>が<ruby>晴<rt>は</rt></ruby>れる",
      "03:42.43 <ruby>忘<rt>わす</rt></ruby>れてしまいたくて<ruby>閉<rt>と</rt></ruby>じ<ruby>込<rt>こ</rt></ruby>めた<ruby>日々<rt>ひび</rt></ruby>に",
      "03:46.70 <ruby>差<rt>さ</rt></ruby>し<ruby>伸<rt>の</rt></ruby>べてくれた<ruby>君<rt>きみ</rt></ruby>の<ruby>手<rt>て</rt></ruby>を<ruby>取<rt>と</rt></ruby>る",
      "03:50.41 <ruby>涼<rt>すず</rt></ruby>しい<ruby>風<rt>かぜ</rt></ruby>が<ruby>空<rt>そら</rt></ruby>を<ruby>泳<rt>およ</rt></ruby>ぐように<ruby>今<rt>いま</rt></ruby><ruby>吹<rt>ふ</rt></ruby>き<ruby>抜<rt>ぬ</rt></ruby>けていく",
      "03:57.10 <ruby>繋<rt>つなが</rt></ruby>いだ<ruby>手<rt>て</rt></ruby>を<ruby>離<rt>はな</rt></ruby>さないでよ",
      "04:00.51 <ruby>二人今<rt>ふたりいま</rt></ruby>、<ruby>夜<rt>よる</rt></ruby>に<ruby>駆<rt>か</rt></ruby>け<ruby>出<rt>だ</rt></ruby>していく",
      "04:04.00 ...",
    ],
  },
  {
    name: "One more time, One more chance",
    url: "res-1/One-more-time-One-more-chance.mp3",
    lyrics: [
      "00:16.40 これ<ruby>以上<rt>いじょぅ</rt></ruby>なにをうしなえば こころはゆるされるの",
      "00:23.90 どれ<ruby>程<rt>ほど</rt></ruby>の<ruby>痛<rt>いた</rt></ruby>みならば もういちどきみにあえる",
      "00:30.60 One more time <ruby>季節<rt>きせつ</rt></ruby>ようつろわないで",
      "00:38.40 One more time ふざけあった<ruby>时间<rt>じかん</rt></ruby>よ",
      "00:46.20 くいちがうときはいつも <ruby>僕<rt>ぼく</rt></ruby>が<ruby>先<rt>さき</rt></ruby>におれたね",
      "00:53.55 わがままな<ruby>性格<rt>せいかく</rt></ruby>が なおさら<ruby>爱<rt>いと</rt></ruby>しくさせた",
      "01:00.30 One more chance <ruby>记忆<rt>きおく</rt></ruby>に<ruby>足<rt>あし</rt></ruby>を<ruby>取<rt>と</rt></ruby>られて",
      "01:08.20 One more chance <ruby>次<rt>つぎ</rt></ruby>の<ruby>场所<rt>ばしょ</rt></ruby>を<ruby>选<rt>えら</rt></ruby>べない",
      "01:15.90 いつでも<ruby>捜<rt>さが</rt></ruby>しているよ どっかに<ruby>君<rt>きみ</rt></ruby>の<ruby>姿<rt>すがた</rt></ruby>を",
      "01:23.20 <ruby>向<rt>むか</rt></ruby>いのホーム <ruby>路地裏<rt>ろじうら</rt></ruby>の<ruby>窓<rt>まど</rt></ruby>",
      "01:26.90 こんなとこにいるはずもないのに",
      "01:30.80 <ruby>愿<rt>ねが</rt></ruby>いがもしも<ruby>叶<rt>かな</rt></ruby>うなら いますぐ<ruby>君<rt>きみ</rt></ruby>のもとへ",
      "01:37.95 できないことは もう<ruby>何<rt>なに</rt></ruby>もない",
      "01:41.80 すべてかけて<ruby>抱<rt>だ</rt></ruby>きしめてみせるよ",
      "01:57.20 <ruby>寂<rt>さび</rt></ruby>しさ<ruby>纷<rt>まぎ</rt></ruby>らすだけなら",
      "02:00.90 <ruby>谁<rt>だれ</rt></ruby>でもいいはずなのに",
      "02:04.60 <ruby>星<rt>ほし</rt></ruby>が<ruby>落<rt>お</rt></ruby>ちそうな<ruby>夜<rt>よる</rt></ruby>だから",
      "02:08.90 <ruby>自分<rt>じぶん</rt></ruby>をいつわれない",
      "02:11.70 One more time <ruby>季節<rt>きせつ</rt></ruby>ようつろわないで",
      "02:19.30 One more time ふざけあった<ruby>时间<rt>じかん</rt></ruby>よ",
      "02:26.90 いつでも<ruby>捜<rt>さが</rt></ruby>しているよ どっかに<ruby>君<rt>きみ</rt></ruby>の<ruby>姿<rt>すがた</rt></ruby>を",
      "02:34.15 <ruby>交差点<rt>こうさてん</rt></ruby>でも <ruby>梦<rt>ゆめ</rt></ruby>の<ruby>中<rt>なか</rt></ruby>でも",
      "02:37.90 こんなとこにいるはずもないのに",
      "02:41.90 <ruby>奇迹<rt>きせき</rt></ruby>がもしも<ruby>起<rt>お</rt></ruby>こるなら いますぐきみに<ruby>见<rt>み</rt></ruby>せたい",
      "02:49.05 <ruby>新<rt>あたら</rt></ruby>しい<ruby>朝<rt>あさ</rt></ruby> これからの<ruby>仆<rt>ぼく</rt></ruby>",
      "02:52.60 <ruby>言<rt>い</rt></ruby>えなかった<ruby>好<rt>す</rt></ruby>きという<ruby>言叶<rt>ことば</rt></ruby>も",
      "03:08.15 <ruby>夏<rt>なつ</rt></ruby>の<ruby>想<rt>おも</rt></ruby>い<ruby>出<rt>で</rt></ruby>がまわる",
      "03:15.80 ふいに<ruby>消<rt>き</rt></ruby>えた<ruby>鼓动<rt>こどう</rt></ruby>",
      "03:23.15 いつでも<ruby>捜<rt>さが</rt></ruby>しているよ どっかに<ruby>君<rt>きみ</rt></ruby>の<ruby>姿<rt>すがた</rt></ruby>を",
      "03:30.80 <ruby>明<rt>あ</rt></ruby>け<ruby>方<rt>がた</rt></ruby>の<ruby>街<rt>まち</rt></ruby> <ruby>桜木町<rt>さくらぎちょう</rt></ruby>で",
      "03:34.55 こんなとこに<ruby>来<rt>く</rt></ruby>るはずもないのに",
      "03:38.20 <ruby>愿<rt>ねが</rt></ruby>いがもしも<ruby>叶<rt>かな</rt></ruby>うなら いますぐ<ruby>君<rt>きみ</rt></ruby>のもとへ",
      "03:45.50 できないことは もう<ruby>何<rt>なに</rt></ruby>もない",
      "03:49.25 すべてかけて<ruby>抱<rt>だ</rt></ruby>きしめてみせるよ",
      "03:53.05 いつでも<ruby>捜<rt>さが</rt></ruby>しているよ どっかに<ruby>君<rt>きみ</rt></ruby>のかけらを",
      "04:00.15 <ruby>旅先<rt>たびさき</rt></ruby>の<ruby>店<rt>みせ</rt></ruby> <ruby>新闻<rt>しんぶん</rt></ruby>の<ruby>隅<rt>すみ</rt></ruby>",
      "04:03.90 こんなとこにあるはずもないのに",
      "04:07.80 <ruby>奇迹<rt>きせき</rt></ruby>がもしも<ruby>起<rt>お</rt></ruby>こるなら いますぐきみに<ruby>见<rt>み</rt></ruby>せたい",
      "04:15.00 <ruby>新<rt>あたら</rt></ruby>しい<ruby>朝<rt>あさ</rt></ruby> これからの<ruby>仆<rt>ぼく</rt></ruby>",
      "04:18.50 <ruby>言<rt>い</rt></ruby>えなかった<ruby>好<rt>す</rt></ruby>きという<ruby>言叶<rt>ことば</rt></ruby>も",
      "04:22.60 いつでも<ruby>捜<rt>さが</rt></ruby>してしまう どっかに<ruby>君<rt>きみ</rt></ruby>の<ruby>笑颜<rt>えがお</rt></ruby>を",
      "04:29.87 <ruby>急行<rt>きゅうこう</rt></ruby><ruby>待<rt>ま</rt></ruby>ちの <ruby>踏切<rt>ふみきり</rt></ruby>あたり",
      "04:33.50 こんなとこにいるはずもないのに",
      "04:37.17 <ruby>命<rt>いのち</rt></ruby>が<ruby>缲<rt>く</rt></ruby>り<ruby>返<rt>かえ</rt></ruby>すならば なんども<ruby>君<rt>きみ</rt></ruby>のもとへ",
      "04:44.50 <ruby>欲<rt>ほ</rt></ruby>しいものなど もう<ruby>何<rt>なに</rt></ruby>もない",
      "04:48.60 <ruby>君<rt>きみ</rt></ruby>のほかに<ruby>大切<rt>たいせつ</rt></ruby>なものなど",
      "04:46.00 ...",
    ],
  },
  {
    name: "春日影",
    url: "res-6/春日影-TV-Version.mp3",
    lyrics: [
      "00:16.00 <ruby>悴<rt>かじ</rt></ruby>かんだ<ruby>心<rt>こころ</rt></ruby> ふるえる<ruby>眼差<rt>まなざ</rt></ruby>し<ruby>世界<rt>せかい</rt></ruby>で",
      "00:23.00 <ruby>僕<rt>ぼく</rt></ruby>はひとりぼっちだった <ruby>散<rt>ち</rt></ruby>ることしか <ruby>知<rt>し</rt></ruby>らない春は",
      "00:33.00 <ruby>毎年<rt>まいとし</rt></ruby><ruby>冷<rt>つめ</rt></ruby>たくあしらう",
      "00:39.00 <ruby>暗<rt>から</rt></ruby>がりの<ruby>中<rt>なか</rt></ruby> <ruby>一方通行<rt>いっぽうつうこう</rt></ruby>にただただ",
      "00:45.00 <ruby>言葉<rt>ことば</rt></ruby>を<ruby>書<rt>か</rt></ruby>き<ruby>殴<rt>なぐ</rt></ruby>って <ruby>期待<rt>きたい</rt></ruby>するだけ むなしいと分かっていても",
      "00:57.00 <ruby>救<rt>すく</rt></ruby>いを<ruby>求<rt>もと</rt></ruby>め<ruby>続<rt>つづ</rt></ruby>けた",
      "01:01.00 せつなくて いとおしい",
      "01:05.00 <ruby>今<rt>いま</rt></ruby>ならば<ruby>分<rt>わ</rt></ruby>かる<ruby>気<rt>き</rt></ruby>がする",
      "01:09.00 しあわせで くるおしい",
      "01:12.00 あの<ruby>日<rt>ひ</rt></ruby><ruby>泣<rt>な</rt></ruby>けなかった<ruby>僕<rt>ぼく</rt></ruby>を<ruby>光<rt>ひかり</rt></ruby>は",
      "01:19.00 やさしく<ruby>連<rt>つ</rt></ruby>れ<ruby>立<rt>だ</rt></ruby>つよ",
      "01:24.00 <ruby>雲間<rt>くもま</rt></ruby>をぬって きらり きらり <ruby>心満<rt>こころみ</rt></ruby>たしては<ruby>溢<rt>あふ</rt></ruby>れ",
      "01:32.00 いつしか<ruby>頬<rt>ほお</rt></ruby>を きらり きらり <ruby>熱<rt>あつ</rt></ruby>く 熱く <ruby>濡<rt>ぬ</rt></ruby>らしてゆく",
      "01:39.00 <ruby>君<rt>きみ</rt></ruby>の<ruby>手<rt>て</rt></ruby>は どうして こんなにも <ruby>温<rt>あたた</rt></ruby>かいの",
      "01:46.00 ねえ お<ruby>願<rt>ね</rt></ruby>い　どうかこのまま",
      "01:52.00 <ruby>離<rt>はな</rt></ruby>さないでいて",
      "01:57.00 <ruby>縁<rt>えん</rt></ruby>を<ruby>結<rt>むす</rt></ruby>んではほどきほどかれ<ruby>誰<rt>だれ</rt></ruby>しもが",
      "02:04.00 それを<ruby>喜<rt>よろこ</rt></ruby>び<ruby>悲<rt>かな</rt></ruby>しみながら<ruby>愛<rt>あい</rt></ruby>を<ruby>",
      "02:11.00 数<rt>かぞ</rt></ruby>えてゆく",
      "02:14.00 <ruby>鼓動<rt>こどう</rt></ruby>を<ruby>確<rt>たし</rt></ruby>かめるように",
      "02:20.00 うれしくて さびしくて",
      "02:23.00 <ruby>今<rt>いま</rt></ruby>だからわかる<ruby>気<rt>き</rt></ruby>がした",
      "02:27.00 たいせつで こわくって",
      "02:30.00 あの<ruby>日<rt>ひ</rt></ruby><ruby>泣<rt>な</rt></ruby>けなかった<ruby>僕<rt>ぼく</rt></ruby>を<ruby>光<rt>ひかり</rt></ruby>は",
      "02:37.00 やさしく<ruby>抱<rt>だ</rt></ruby>きしめた",
      "02:42.00 -",
      "02:57.00 <ruby>照<rt>て</rt></ruby>らされた<ruby>世界<rt>せかい</rt></ruby>　<ruby>咲<rt>さ</rt></ruby>き<ruby>誇<rt>ほこ</rt></ruby>る<ruby>大切<rt>たいせつ</rt></ruby>な<ruby>人<rt>ひと</rt></ruby>",
      "03:04.00 あたたかさを<ruby>知<rt>し</rt></ruby>った<ruby>春<rt>はる</rt></ruby>は<ruby>僕<rt>ぼく</rt></ruby>のため<ruby>君<rt>きみ</rt></ruby>のための",
      "03:09.00 <ruby>涙<rt>なみだ</rt></ruby>を<ruby>流<rt>なが</rt></ruby>すよ",
      "03:12.00 あぁ　なんて<ruby>眩<rt>まぶ</rt></ruby>しいんだろう",
      "03:16.00 あぁ　なんて<ruby>美<rt>うつく</rt></ruby>しいんだろう",
      "03:23.00 -",
      "03:33.00 <ruby>雲間<rt>くもま</rt></ruby>をぬって きらり きらり <ruby>心満<rt>こころみ</rt></ruby>たしては<ruby>溢<rt>あふ</rt></ruby>れ",
      "03:41.00 いつしか<ruby>頬<rt>ほお</rt></ruby>を きらり きらり <ruby>熱<rt>あつ</rt></ruby>く 熱く <ruby>濡<rt>ぬ</rt></ruby>らしてゆく",
      "03:48.00 <ruby>君<rt>きみ</rt></ruby>の<ruby>手<rt>て</rt></ruby>は どうして こんなにも <ruby>温<rt>あたた</rt></ruby>かいの",
      "03:55.00 ねえ お<ruby>願<rt>ね</rt></ruby>い　どうかこのまま",
      "04:02.00 <ruby>離<rt>はな</rt></ruby>さないでいて",
      "04:05.00 ずっと　ずっと",
      "04:09.00 <ruby>離<rt>はな</rt></ruby>さないでいて",
      "04:14.00 -",
    ],
  },
];
